/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
  // Disable ISR

  // Set VTOR to new interrupt table
  *(uint32_t *)(0xE000ED08UL) = 0x2000;
//  uint32_t register fwStartAddress = *(uint32_t *)0x8002004;
  asm volatile (
      "ldr r0, =#0x8002004\n\t"
      "ldr r1, [r0]\n\t"
      "bx %r1\n\t"
  );

    /* Loop forever */
	for(;;);
}
